---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpinehelloworld-deployment
  namespace: cicd
  labels:
    app: alpinehelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpinehelloworld
  template:
    metadata:
      labels:
        app: alpinehelloworld
    spec:
      containers:
        - name: alpinehelloworld
          image: dirane/alpinehelloworld
          env:
            - name: PORT
              value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: alpinehelloworld-service
  namespace: cicd
spec:
  type: NodePort
  selector:
    app: alpinehelloworld
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
